api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
mapboxjs: v1.6.1
oldversion: v0.6.7
title: Mapbox.js
defaultid: 'examples.map-9ijuk24y'
description: Mapbox JavaScript API
exclude: [node_modules, build.sh, config.ru, Gemfile, Gemfile.lock, generate.js, header, leaflet-reference.html, package.json]
rdiscount:
  extensions: [smart]
